import Head from "next/head";
import Image from "next/image";
import { Button, Divider, Stack, Typography, colors } from "@mui/material";
import styles from "@styles/index.module.css";
import Link from "next/link";
import ContentsList from "@src/components/ContentsList";
import { useState, useEffect } from "react";

export default function Home() {
  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  const imageArray = [
    "/hero/hero1.jpg",
    "/hero/hero2.jpg",
    "/hero/hero3.jpg",
    "/hero/hero4.jpg",
    "/hero/hero5.jpg",
    "/hero/hero6.jpg",
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentImageIndex((prevIndex) => (prevIndex + 1) % imageArray.length);
    }, 5000); // Change image every 5 seconds

    return () => clearInterval(interval);
  }, [imageArray.length]);

  return (
    <>
      <Head>
        <title>Projeto 60 mais</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.heroWrapper}>
          <div className={styles.heroContent}>
            <Link href="#content" passHref scroll={false}>
              <Button
                style={{ scrollBehavior: "smooth" }}
                LinkComponent={"a"}
                variant={"contained"}
                color={"primary"}
              >
                Acessar conteúdos
              </Button>
            </Link>
            <Divider
              sx={{
                my: 2,
                width: "100%",
                borderColor: "white",
              }}
            />
          </div>

          <Image
            priority={true}
            src={imageArray[currentImageIndex]}
            alt="Imagem de fundo contendo sêniors utilizando tecnologia"
            fill
            style={{
              backgroundColor: "white",
              objectFit: "cover",
              objectPosition: "center",
              zIndex: "-1",
              position: "absolute",
            }}
          />
        </div>

        <ContentsList />
      </main>
    </>
  );
}
